name: Build
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run build
        run: yarn build
